import { useNavigate, useLocation } from 'react-router-dom'
import { dashboardCss } from '../../components/dashboard/dashboardStyles'
import { LockIcon, DocumentIcon } from '../../components/icons'

// ─── Content ─────────────────────────────────────────────────────────────────────
const TERMS_SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using Blorbmart, you agree to be bound by these Terms of Service. If you do not agree to all terms, you may not use the platform.',
  },
  {
    title: '2. Eligibility',
    body: 'Blorbmart is intended for use by university students and campus-based vendors. You must be at least 16 years old and enrolled at or affiliated with a participating institution.',
  },
  {
    title: '3. User Accounts',
    body: 'You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. Blorbmart is not liable for losses arising from unauthorized access due to your negligence.',
  },
  {
    title: '4. Buyer Responsibilities',
    body: 'Buyers must provide accurate delivery addresses and contact information. Orders placed are binding; cancellations may only be made before the seller confirms the order. Buyers agree not to abuse the refund or dispute system.',
  },
  {
    title: '5. Payments & Wallet',
    body: 'All payments are processed securely via Paystack. Wallet funds are non-transferable and may only be used for purchases on Blorbmart. Blorbmart is not a financial institution and does not pay interest on wallet balances.',
  },
  {
    title: '6. Refunds & Disputes',
    body: 'Refund requests must be submitted within 24 hours of delivery. Blorbmart will mediate disputes between buyers and sellers in good faith. Decisions made by Blorbmart during dispute resolution are final.',
  },
  {
    title: '7. Prohibited Conduct',
    body: 'You may not use Blorbmart to sell illegal goods, harass other users, manipulate reviews, create fraudulent orders, or attempt to circumvent platform fees. Violations may result in immediate account suspension.',
  },
  {
    title: '8. Limitation of Liability',
    body: 'Blorbmart provides the platform "as is." We are not liable for losses resulting from seller non-performance, delivery delays, or force majeure events. Our maximum liability is limited to the amount of your last transaction.',
  },
  {
    title: '9. Changes to Terms',
    body: 'We reserve the right to update these terms at any time. Continued use of Blorbmart after changes are posted constitutes acceptance of the new terms.',
  },
  {
    title: '10. Contact',
    body: 'For questions about these terms, contact us at legal@blorbmart.com.ng.',
  },
]

const PRIVACY_SECTIONS = [
  {
    title: '1. Information We Collect',
    body: 'We collect information you provide directly (name, email, phone, address), information generated by your use of the platform (orders, transactions, search history), and technical data (device type, IP address, browser).',
  },
  {
    title: '2. How We Use Your Information',
    body: 'Your information is used to process orders, verify payments, provide customer support, send relevant notifications, improve platform features, and comply with legal obligations.',
  },
  {
    title: '3. Sharing Your Information',
    body: 'We share your information with sellers and riders only to fulfil your orders, with Paystack to process payments, and with government authorities when required by law. We do not sell your data to third parties.',
  },
  {
    title: '4. Data Retention',
    body: 'We retain your account data for as long as your account is active. Transaction records are kept for at least 5 years for compliance purposes. You may request deletion of non-essential data at any time.',
  },
  {
    title: '5. Cookies & Tracking',
    body: 'Blorbmart uses cookies and similar technologies to keep you logged in, remember preferences, and understand how users navigate the platform. You can disable cookies in your browser settings, but some features may not work correctly.',
  },
  {
    title: '6. Security',
    body: 'We use industry-standard encryption (TLS) for data in transit and restrict access to personal data to authorized staff only. However, no system is 100% secure, and we cannot guarantee absolute security.',
  },
  {
    title: '7. Your Rights',
    body: 'You have the right to access, correct, or delete your personal data. You may also object to processing or request a portable copy of your data. To exercise these rights, contact us at privacy@blorbmart.com.ng.',
  },
  {
    title: '8. Children\'s Privacy',
    body: 'Blorbmart is not intended for users under 16. We do not knowingly collect personal data from children. If you believe a child has created an account, please contact us for immediate removal.',
  },
  {
    title: '9. Changes to This Policy',
    body: 'We may update this Privacy Policy periodically. We will notify you via email or in-app notification when significant changes occur.',
  },
  {
    title: '10. Contact Us',
    body: 'For privacy-related enquiries, contact our Data Officer at privacy@blorbmart.com.ng.',
  },
]

// ─── CSS ─────────────────────────────────────────────────────────────────────────
const css = `
  .lg-root { min-height:100vh; background:var(--bg); font-family:'Plus Jakarta Sans',sans-serif; }

  .lg-header { position:sticky; top:0; z-index:30; background:rgba(255,255,255,.95); backdrop-filter:blur(8px);
    border-bottom:1.5px solid var(--border); padding:14px 20px; display:flex; align-items:center; gap:12px; }
  .lg-back { width:36px; height:36px; border-radius:50%; border:1.5px solid var(--border); background:#fff;
    display:flex; align-items:center; justify-content:center; cursor:pointer; flex-shrink:0; }
  .lg-header-title { font-family:'Bricolage Grotesque',sans-serif; font-size:18px; font-weight:800; flex:1; text-align:center; }

  .lg-body { max-width:640px; margin:0 auto; padding:24px 20px 80px; }

  .lg-intro { background:#fff; border:1.5px solid var(--border); border-radius:var(--radius-lg); padding:20px;
    margin-bottom:24px; display:flex; gap:14px; align-items:flex-start; }
  .lg-intro-icon { font-size:32px; }
  .lg-intro-title { font-family:'Bricolage Grotesque',sans-serif; font-size:16px; font-weight:800; color:var(--text); margin-bottom:4px; }
  .lg-intro-date { font-size:12px; color:var(--text-2); }

  .lg-section { background:#fff; border:1.5px solid var(--border); border-radius:var(--radius-lg);
    padding:18px 20px; margin-bottom:10px; }
  .lg-section-title { font-size:13px; font-weight:800; color:var(--text); margin-bottom:8px; }
  .lg-section-body { font-size:13px; color:var(--text-2); line-height:1.65; }

  .lg-tabs { display:flex; gap:0; margin-bottom:24px; background:var(--bg); border:1.5px solid var(--border);
    border-radius:var(--radius); overflow:hidden; }
  .lg-tab { flex:1; padding:11px; text-align:center; font-size:13px; font-weight:700; cursor:pointer;
    background:none; border:none; font-family:'Plus Jakarta Sans',sans-serif; color:var(--text-2); }
  .lg-tab.active { background:var(--blue); color:#fff; }
`

// ─── Main Component ─────────────────────────────────────────────────────────────
export function LegalPage() {
  const navigate  = useNavigate()
  const location  = useLocation()
  const isPrivacy = location.pathname === '/privacy'
  const sections  = isPrivacy ? PRIVACY_SECTIONS : TERMS_SECTIONS
  const title     = isPrivacy ? 'Privacy Policy' : 'Terms of Service'
  const Icon      = isPrivacy ? LockIcon : DocumentIcon
  const lastUpdate = isPrivacy ? 'Last updated: January 2025' : 'Last updated: January 2025'

  const switchTo = (path: string) => navigate(path, { replace: true })

  return (
    <>
      <style>{dashboardCss}</style>
      <style>{css}</style>

      <div className="lg-root">
        <header className="lg-header">
          <button className="lg-back" type="button" onClick={() => navigate(-1)}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="15 18 9 12 15 6"/>
            </svg>
          </button>
          <span className="lg-header-title">{title}</span>
          <div style={{ width: 36 }} />
        </header>

        <div className="lg-body">
          {/* Tab switcher */}
          <div className="lg-tabs">
            <button
              type="button"
              className={`lg-tab${!isPrivacy ? ' active' : ''}`}
              onClick={() => switchTo('/terms')}
            >
              Terms of Service
            </button>
            <button
              type="button"
              className={`lg-tab${isPrivacy ? ' active' : ''}`}
              onClick={() => switchTo('/privacy')}
            >
              Privacy Policy
            </button>
          </div>

          {/* Intro card */}
          <div className="lg-intro">
            <div className="lg-intro-icon"><Icon /></div>
            <div>
              <div className="lg-intro-title">{title}</div>
              <div className="lg-intro-date">{lastUpdate}</div>
            </div>
          </div>

          {/* Sections */}
          {sections.map((s, i) => (
            <div key={i} className="lg-section">
              <div className="lg-section-title">{s.title}</div>
              <div className="lg-section-body">{s.body}</div>
            </div>
          ))}
        </div>
      </div>
    </>
  )
}
